In this notebook we are going to cover some of the most fundamental concepts
of tensors uning TensorFlow
more specifically, we're going to cover:


In [173]:
#Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.12.0


In [174]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [175]:
#check the number of dimensions of  a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [176]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [177]:
# Check the dimension of the vector
vector.ndim

1

In [178]:
# Creating a matrix (having more than 1 dimensions)
matrix = tf.constant([[10, 7], [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [179]:
matrix.ndim

2

In [180]:
# Creating another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype = tf.float16) # Specify the data type with dtype parameter
# The dtypeN here N = number of bytes of the data type you want to store in the memory
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [181]:
# shape = (no. of elements in the array, no of the dimentions of the array),
# dtype = data type of the data stored , scalar have no dimentions and a 
# vector can have only a single dimention

tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]], 
                       [[7, 8, 9],
                        [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [182]:
tensor.ndim

3

### Created so far:
* Scalar: a single number
* Vector: a number(magnitude) with direction(e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimentional array of number (where n can be any number, a 0-dimentional array is a Scalar and a 
1-dimentional array is a Vector)

### Creating tensors with `tf.Variable`

In [183]:
# Create the same tensor with tf.Variable as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

#### Let's change the value of the elements in the changeable tensor

changeable_tensor[0] = 7
changeable_tensor
#### The above code will not execute

In [184]:
# Trying .assign() to add values in the changeable tensor
changeable_tensor[0].assign(7)
changeable_tensor 


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [185]:
# Lets try to change the unchangable tensor
# unchangable_tensor[0].assign(7)
# unchangable_tensor

**note:** Rarely in practice you will need to decide whether you need to use `tf.constant` or `tf.Variable` to create tensors as TensorFlow do that for you. However, if in doubt use `tf.constant` and change it later if needed.

### Creating random tensors

Random tensors are tensors of some arbitraty size which contain random numbers.

1. Initialize with random weights (only at beginning)

In [186]:
import tensorflow as tf

# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) 
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (3, 2))
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor
So that the neural network do not confuse the types of inputs given rather than learning only a type 

**tensorflow uses two types of seeds global level seeds and the operation level seeds and the global and the operation level seed are required for the pseudo random outputs and if either of them are not provided a random output will be generated every time it is executed and tensorflow will automatically take a seed to generate the outputs**

In [187]:
# Shuffle a tensor(for when you want to shuffle the data so that the inherent data do not interfere)
not_shuffled = tf.constant([[10, 7], 
                            [3, 4],
                            [2, 5]])
# Shuffle our non-shuffled data
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [188]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [189]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [190]:
# 5 random tensors

a = tf.random.Generator.from_seed(42)
a = a.normal(shape=(3, 2))
b = tf.random.Generator.from_seed(42)
b = b.normal(shape=(4, 2))
c = tf.random.Generator.from_seed(42)
c = c.normal(shape=(1,4))
d = tf.random.Generator.from_seed(42)
d = d.normal(shape=(5, 2))
e = tf.random.Generator.from_seed(42)
e = e.normal(shape=(1,2))
a, b, c, d, e
# or a better way of doing this is 


t = tf.random.shuffle(a, seed = 79)
e = tf.random.shuffle(a, seed = 4)
ta = tf.random.shuffle(a, seed = 90)
d = tf.random.shuffle(a, seed = 6)
y = tf.random.shuffle(a, seed = 7)

t, e, ta, d, y


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [-0.23193763, -1.8107855 ],
        [ 0.07595026, -1.2573844 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.23193763, -1.8107855 ],
        [-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.07595026, -1.2573844 ],
        [-0.7565803 , -0.06854702],
        [-0.23193763, -1.8107855 ]], dtype=float32)>)

` you can use the ctrl+ shift + enter to know the info about the function used`

# Other ways to make tensors

In [191]:
# 1. tensors of ones
tf.ones([2,2])
# 2. tensors of zeros
tf.zeros(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [192]:
tf.ones(shape = (3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

### Turn NumPy arrays into tensors

The main difference b/w the NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU (much faster for numerical computing)

In [193]:
# Turning NumPy arrays into tensors
import numpy as np
numpy_A  = np.arange(1, 25, dtype = np.int32)
A = tf.constant(numpy_A)
# A
B = tf.Variable(numpy_A)
# B[7].assign(69)
B
# X = tf.constant(<some matrix>) # capital for matrix or tensor
# y - tf.constant (vector) # non - capital for vectors

<tf.Variable 'Variable:0' shape=(24,) dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [194]:
 A = tf.constant(numpy_A, shape=(2, 3, 4))
 B = tf.constant(numpy_A)
 A = tf.constant(numpy_A, shape=(3, 8))
 A, B

(<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

# Getting information from tensors

We would require the following attributes :-
* Shape(tensor.shape)- The lenght(number of elements) of each of the dimensions of a tensor
* Rank(tensor.ndim)- A scalar have a rank 0, A vecor have a rank 1, A matrix have a rank 2 and a tensor have a rank n

* Axis or dimension(tensor[0], tensor[:,1]...)- A paticular dimension of a tensor
* Size (tf.size(tensor))- The total number of items in the tensor

In [195]:
# Creating a rank 4 tensor(4 dimentions)
rank_4_tensor = tf.ones(shape = [2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]], dtype=float32)>

In [196]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float32)>

In [197]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [198]:
# Get various attributes of our tensor
print("Datatype of every element: ", rank_4_tensor.dtype)
print("Number of dimentions (rank): ", rank_4_tensor.ndim)
print("Shape of tensor: ", rank_4_tensor.shape)
print("Elements along the 0 axis: ", rank_4_tensor.shape[0])
print("Elements along the last axis: ", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor: ", tf.size(rank_4_tensor).numpy())

Datatype of every element:  <dtype: 'float32'>
Number of dimentions (rank):  4
Shape of tensor:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis:  5
Total number of elements in our tensor:  120


### Indexing tensors

Tensors can be indexed similar to pyton lists.

In [199]:
# Get the first two elements of each dimension.
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]], dtype=float32)>

In [200]:
# Get the first element from each dimention from each index except for the final one

rank_4_tensor[:1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[1., 1., 1., 1., 1.]]]], dtype=float32)>

In [201]:
rank_4_tensor[:1, :1, :, :1]#'This generates a tensor with first element from each dimention except for the third dimention'

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[1.],
         [1.],
         [1.],
         [1.]]]], dtype=float32)>

In [202]:
# Create a rank 2 tensor (2 dimention)

rank_2_tensor = tf.constant([[10, 7], 
                             [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [203]:
# Get the last item of each of our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [204]:
# Adding extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]# the ... represent the [:, :, tf.newaxis]

In [205]:
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [206]:
# Alernative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis = -1)# '-1'means to expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [207]:
tf.expand_dims(rank_2_tensor, axis = 0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

### Manipulating tensors (tensor operations)

**Basic operations**
`+`, `-`, `/`, `*`

In [208]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10, 7], [3, 4]])
print(tensor + 10) # after this the original tensor is unchanged 
tensor

tf.Tensor(
[[20 17]
 [13 14]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [209]:
# Multiplicaiton also works
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [210]:
# We can use the tensorflow builtin funcitons too
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

###**Matrix** multiplication

**In machine learning the matrix multiplication is the most commmon tensor operations.**

There are two rules that the tensors have ot follow:- 
* The inner dimensions must match
* The resulting matrix has the shape of the outer dimensions

In [211]:
import tensorflow as tf
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [212]:
# Matrix multiplication with Python operator "@"
tensor @ tensor
# The @ operator in Python represents the matrix multiplication

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [213]:
tensor.shape

TensorShape([2, 2])

In [214]:
# Creating a (3, 2) tensor
X = tf.constant([[1, 2], 
                 [3, 4],
                 [5, 6]])
# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
Y = tf.reshape(Y, (2,3))
X @ Y
# X = tf.constant([1, 2, 5, 7, 2, 1, 3, 3, 3], shape=(3, 3))
# Y = tf.constant([3, 5, 6, 7, 1, 8, 2, 6, 7], shape=(3, 3))
# # Y = tf.constant([3, 5, 6, 7, 1, 8, 2, 6], shape=(4, 2))
# print(tf.matmul(X, Y))
# X @ Y

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [215]:
tf.matmul(X, Y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [216]:
X = tf.constant([[1, 2], 
                 [3, 4],
                 [5, 6]])
Y = tf.constant([3, 5, 6, 7, 1, 8], shape=(3, 2))
X @ tf.reshape(Y, shape= (2, 3))


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[17,  7, 22],
       [37, 19, 50],
       [57, 31, 78]], dtype=int32)>

In [217]:
 X.shape, tf.reshape(Y, shape= (2, 3))

(TensorShape([3, 2]),
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[3, 5, 6],
        [7, 1, 8]], dtype=int32)>)

In [218]:
tf.matmul(tf.reshape(X, shape= (2,3)), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 18,  43],
       [ 48, 103]], dtype=int32)>

In [219]:
# Can do the same with transpose 
X, tf.transpose(X), tf.reshape(X, shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [220]:
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[26, 66],
       [36, 86]], dtype=int32)>

**The difference between a transpose and a reshape is that a reshape is shuffling the in the shape as you want whereas the transpose only switch the rows as well as the columns**

In [221]:
# Trying the matrix multiplication with the transpose rather than reshape

X = tf.constant([[1, 2], 
                 [3, 4],
                 [5, 6]])

Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

**The dot product**

Matrix multiplication is also referred to as the dot product.

The dot product can be performed via.
  * `tf.matmul()`
  *`tf.tensordot()`
  * `@`

In [222]:
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [223]:
# Perform the dot product on X and Y (requires X or Y to be transposed)
tf.tensordot(tf.transpose(X), Y, axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [224]:
# Perform matrix multiplication  between X and Y (transposed)

tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [225]:
#perform matrix multiplicaiton between X and Y (reshape)
tf.matmul(X, tf.reshape(Y , shape = (2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [226]:
# Check the vlaues of Y , reshape Y and transposed Y 
print("Noraml Y:")
print(Y, "\n")
print("Y reshaped to (2, 3):")
print(tf.reshape(Y, (2, 3)), "\n")
print("Y transposed:")
print(tf.transpose(Y))


Noraml Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [227]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

Generally, when performing matrix multiplicaiton on two tensors and one of the axes doesn't line up, you will transpose (rather than reshape) one of the tensors to get satisfy the matrix multiplication rules.

### Changing the data type of the tensor

In [228]:
tf.__version__

'2.12.0'

In [229]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])
B, B.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 tf.float32)

In [230]:
C = tf.constant([7, 10])
C.dtype

tf.int32

In [231]:
# Change from float32 to float16(reduced precision) 
# The reduction from the 32 to 16 is faster in most of the mordern hardware 'cause the 16 bit operations are 

D = tf.cast(B, dtype = tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [232]:
# Change from int32 to float32
E = tf.cast(C, dtype = tf.float16)
E

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

### Aggregating tensors

Aggregating tensors = condensing the multiple values to a smaller amount of values

In [233]:
# Get the absolute values
D = tf.constant([-7, -10])
D


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [234]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

### Let's go through the following forms of aggregation:
* Get the minimun
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor


In [235]:
god = tf.random.Generator.from_seed(42)
god = god.normal(shape = (3, 4))
god

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646],
       [-0.7535805 , -0.57166284,  0.1480774 , -0.23362993]],
      dtype=float32)>

In [236]:
# Create a random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0, 100, size = 50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([20, 32, 46, 14, 27, 37, 69, 70, 28, 81, 74, 76, 45, 60, 98, 87, 70,
       39, 43, 39,  5, 43, 57, 87, 74, 28, 38, 39,  5, 93, 68, 39, 73, 29,
        8, 78, 61, 82, 65,  4,  8, 60, 63, 85,  6, 91, 89, 18, 26, 14])>

In [237]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=4>

In [238]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [239]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=49>

In [240]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2491>

In [241]:
# method 1 to find the variance of a tensor
import tensorflow_probability as tfp
tfp.stats.variance(E)


<tf.Tensor: shape=(), dtype=int64, numpy=772>

In [242]:
# method 2 to find the standard deviation of a tensor
tf.math.reduce_variance(tf.cast(E, dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=772.2276>

In [243]:
# finding the standard deviation of a tensor
tf.math.reduce_std(tf.cast(E, dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=27.788984>

### Finding the positinal maximum and minimum

In [244]:
tf.random.set_seed(42)
F = tf.random.uniform(shape = [50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [245]:
# finding the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [246]:
# Index on our largest value positional 
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [247]:
# Find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [248]:
# Check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [249]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [250]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [251]:
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [252]:
F[tf.argmin(F)] == tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [253]:
mine_tensor = tf.ones(shape = [4, 5])

In [254]:
mine_tensor

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [255]:
tf.argmax(mine_tensor)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([0, 0, 0, 0, 0])>

In [256]:
len(tf.argmax(mine_tensor))

5

In [260]:
mine_tensor = tf.random.Generator.from_seed(25)
mine_tensor = mine_tensor.normal(shape = (4, 5))

In [261]:
mine_tensor

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[-0.14371012, -0.34646833,  1.1456194 , -0.416     ,  0.43369916],
       [ 1.0241015 , -0.74785167, -0.59090924, -1.2060374 ,  0.8307429 ],
       [ 1.0951619 ,  1.3672234 , -0.54532146,  1.9302735 , -0.3151453 ],
       [-0.8761205 , -2.7316678 , -0.15730922,  1.3692921 , -0.4367834 ]],
      dtype=float32)>

In [262]:
tf.argmax(mine_tensor)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([2, 2, 0, 2, 1])>

In [263]:
tf.argmin(mine_tensor)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([3, 3, 1, 1, 3])>

In [264]:
tf.reduce_min(mine_tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=-2.7316678>

In [265]:
tf.reduce_max(mine_tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=1.9302735>

### Squeezing a tensor(removing all single dimenstions)

In [270]:
# Creating a tensor 
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape = [50]), shape =(1, 1, 1, 1, 50))

In [271]:
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [272]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [277]:
G_squeezed = tf.squeeze(G)

In [278]:
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

### One-hot encoding tensors

In [279]:
# Creating a listof indices
some_list = [0, 1, 2, 3] # could be red , green, blue, purple 

# One hot encode our list of indices
tf.one_hot(some_list, depth = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [282]:
# Specify custom values for one hot encoding 
tf.one_hot(some_list, depth =4 , on_value="It's", off_value="2 o'clock at night")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b"It's", b"2 o'clock at night", b"2 o'clock at night",
        b"2 o'clock at night"],
       [b"2 o'clock at night", b"It's", b"2 o'clock at night",
        b"2 o'clock at night"],
       [b"2 o'clock at night", b"2 o'clock at night", b"It's",
        b"2 o'clock at night"],
       [b"2 o'clock at night", b"2 o'clock at night",
        b"2 o'clock at night", b"It's"]], dtype=object)>

### Squring, log and square root


In [285]:
# Creating a new tensor
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [286]:
# Squring it 
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [289]:
# Finding squareroot
tf.sqrt(tf.cast(H, dtype = 'float16'))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)>

In [292]:
tf.math.log(tf.cast(H, dtype = 'float16'))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
       2.197 ], dtype=float16)>

### Tensors and numpy

In [293]:
# Creating a tensor form numpy array 
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [294]:
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [298]:
# Convert tensor J to a NumPy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [300]:
# The default types of each are slightly different
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])

In [301]:
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

# Making sure that our tensors run really fast on GPU's

## Tensors vs NumPy
Altough tensorflow interacts beautifully with NumPy arrays.
The main difference among the two are 
* Tensor use the GPU for really fast numerical processing
* Whereas NumPy is optimised in C therefore it interacts with the hardware very easily and provide fast processign rather than the original python lists.

## Finding access to the GPU's

In [4]:
import tensorflow as tf

tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [10]:
!nvidia-smi

Mon Jun  5 08:52:33 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   42C    P8     9W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

If we have access to a CUDA-enabled GPU, TensorFlow will automatically use it whenever possible.